spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop

aws:
  profile: dev
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: aaa

server:
  address: 0.0.0.0
  port: 8080