# name: Packer Machine Image Build

# on:
#   workflow_run:
#     workflows: ["Webapp CI"]
#     types:
#       - completed

# jobs:
#   build-mi:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Download Artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: webapp
#           path: packer/artifacts

#       - name: Setup AWS CLI
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Install Packer
#         uses: hashicorp/setup-packer@main
#         with:
#           version: 'latest'
      
#       - name: Initialize Packer
#         run: |
#           cd packer
#           packer init .

#       - name: Build Machine Image
#         run: |
#           cd packer
#           packer build -var-file=dev.pkrvars.hcl