name: Packer Custom Image CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest

      - name: Initialize packer
        run: packer init packer/

      - name: Run packer fmt
        id: fmt
        run: packer fmt -check packer/.

      - name: Run packer validate
        id: validate
        run: packer validate packer/.